# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sua_clinica_db
spring.datasource.username=usuario_backend_app
spring.datasource.password=SuaSenhaSuperSecreta
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/clinica_prontuarios

# Server port (optional)
server.port=8080
