package com.example.cadastro.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "consultas")
public class Consulta {
    @Id
    @Column(length = 50)
    private String id_consulta; // generated by function

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_animal")
    private Animal animal;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_veterinario")
    private Usuario veterinario;

    private LocalDateTime data_hora;

    @Column(length = 20)
    private String status;

    public String getId_consulta() { return id_consulta; }
    public void setId_consulta(String id_consulta) { this.id_consulta = id_consulta; }

    public Animal getAnimal() { return animal; }
    public void setAnimal(Animal animal) { this.animal = animal; }

    public Usuario getVeterinario() { return veterinario; }
    public void setVeterinario(Usuario veterinario) { this.veterinario = veterinario; }

    public LocalDateTime getData_hora() { return data_hora; }
    public void setData_hora(LocalDateTime data_hora) { this.data_hora = data_hora; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
}
