package com.example.cadastro.model;

import jakarta.persistence.*;

@Entity
@Table(name = "usuarios")
public class Usuario {
    @Id
    @Column(length = 50)
    private String id_usuario; // generated by function

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_grupo")
    private GrupoUsuario grupo;

    @Column(nullable = false, length = 100)
    private String nome;

    @Column(unique = true, nullable = false, length = 100)
    private String email;

    @Column(nullable = false, length = 255)
    private String hash_senha;

    @Column(nullable = false)
    private Boolean ativo = true;

    public String getId_usuario() { return id_usuario; }
    public void setId_usuario(String id_usuario) { this.id_usuario = id_usuario; }

    public GrupoUsuario getGrupo() { return grupo; }
    public void setGrupo(GrupoUsuario grupo) { this.grupo = grupo; }

    public String getNome() { return nome; }
    public void setNome(String nome) { this.nome = nome; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getHash_senha() { return hash_senha; }
    public void setHash_senha(String hash_senha) { this.hash_senha = hash_senha; }

    public Boolean getAtivo() { return ativo; }
    public void setAtivo(Boolean ativo) { this.ativo = ativo; }
}
